# Generated by Django 4.1.5 on 2023-01-28 06:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twitter', '0003_twee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Twee',
            new_name='Tweet',
        ),
    ]
